// This file is auto-generated by build.py — do not edit manually.
// Run: python build.py to regenerate.

export interface TrendSource {
  name: string;
  url: string;
}

export interface TrendIntelligence {
  name: string;
  momentum_score: number;
  acceleration: "fast" | "steady" | "slowing";
  stage: "emerging" | "accelerating" | "mainstream" | "declining";
  time_horizon: "short" | "mid" | "long";
  market_impact: "niche" | "growing" | "mainstream" | "aspirational";
  confidence_score: number;
  key_insight: string;
  action: string;
  risk: string;
}

export interface Trend {
  rank: number;
  name: string;
  category: string;
  lifecycle: string;
  score: number;
  source_count: number;
  what?: string;
  why_now?: string;
  how?: string[];
  sources?: TrendSource[];
  intelligence?: TrendIntelligence;
}

export interface ColorTrend {
  name: string;
  status: string;
  where: string;
  combo: string;
}

export interface Alert {
  title?: string;
  reason?: string;
  source_name?: string;
  source_url?: string;
}

export interface FabricTrend {
  name: string;
  direction: string;
  usage: string;
}

export interface NextWeekItem {
  title: string;
  desc: string;
}

export interface ReportData {
  meta: {
    author?: string;
    period?: string;
    sources?: string;
    status?: string;
  };
  highlights: { title: string; desc: string }[];
  trends: Trend[];
  colors: ColorTrend[];
  fabrics: FabricTrend[];
  next_week: NextWeekItem[];
  alert: Alert | null;
  has_intelligence: boolean;
  trend_count: number;
  top_score: number;
  report_file: string;
}
